name: my-frontend

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockdoinkorea/community-frontend:latest
    container_name: my-frontend
    ports:
      - "3000:3000"
    restart: on-failure:5
    environment:
      API_TARGET: http://backend:8080
    networks:
      - my-community-net

networks:
  my-community-net:
    external: true
